import z3

smt_logic = """
; insert the auto-generated code here
; SMT-LIBv2 description generated by Yosys 0.61+97 (git sha1 1f6a13dac, clang++ 18.1.8 -fPIC -O3)
; yosys-smt2-stbv
; yosys-smt2-module poly_wrapper
(define-sort |poly_wrapper_s| () (_ BitVec 11))
(define-fun |poly_wrapper_is| ((state |poly_wrapper_s|)) Bool (= ((_ extract 0 0) state) #b1))
(define-fun |poly_wrapper#0| ((state |poly_wrapper_s|)) (_ BitVec 8) ((_ extract 8 1) state)) ; x
(define-fun |poly_wrapper#1| ((state |poly_wrapper_s|)) (_ BitVec 10) (bvsub #b0100000000 (concat #b00 (|poly_wrapper#0| state)))) ; { $flattenmod.$sub$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:50$10_Y [16] $flattenmod.$sub$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:50$10_Y [8:0] }
(define-fun |poly_wrapper#2| ((state |poly_wrapper_s|)) (_ BitVec 17) (bvmul (concat ((_ extract 9 9) (|poly_wrapper#1| state)) (concat ((_ extract 9 9) (|poly_wrapper#1| state)) (concat ((_ extract 9 9) (|poly_wrapper#1| state)) (concat ((_ extract 9 9) (|poly_wrapper#1| state)) (concat ((_ extract 9 9) (|poly_wrapper#1| state)) (concat ((_ extract 9 9) (|poly_wrapper#1| state)) (concat ((_ extract 9 9) (|poly_wrapper#1| state)) (|poly_wrapper#1| state)))))))) (concat #b000000000 (|poly_wrapper#0| state)))) ; mod.z
(define-fun |poly_wrapper#3| ((state |poly_wrapper_s|)) Bool (bvugt (|poly_wrapper#2| state) #b01111111111111111)) ; $flattenmod.$gt$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:54$12_Y
(define-fun |poly_wrapper#4| ((state |poly_wrapper_s|)) (_ BitVec 17) (ite (|poly_wrapper#3| state) #b01111111111111111 (|poly_wrapper#2| state))) ; $flattenmod.$ternary$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:54$13_Y
(define-fun |poly_wrapper#5| ((state |poly_wrapper_s|)) (_ BitVec 2) ((_ extract 10 9) state)) ; { sel1 sel2 }
(define-fun |poly_wrapper#6| ((state |poly_wrapper_s|)) Bool (= (|poly_wrapper#5| state) #b10)) ; $flattenmod.$procmux$15_CMP
(define-fun |poly_wrapper#7| ((state |poly_wrapper_s|)) Bool (= (|poly_wrapper#5| state) #b01)) ; $flattenmod.$procmux$16_CMP
(define-fun |poly_wrapper#8| ((state |poly_wrapper_s|)) Bool (not (or  (= ((_ extract 0 0) (|poly_wrapper#5| state)) #b1) (= ((_ extract 1 1) (|poly_wrapper#5| state)) #b1)))) ; $flattenmod.$procmux$17_CMP
(define-fun |poly_wrapper#9| ((state |poly_wrapper_s|)) Bool (= (|poly_wrapper#5| state) #b11)) ; $flattenmod.$procmux$18_CMP
(define-fun |poly_wrapper#10| ((state |poly_wrapper_s|)) (_ BitVec 17) (ite (|poly_wrapper#9| state) (|poly_wrapper#4| state) (ite (|poly_wrapper#8| state) #b00000000000000000 (ite (|poly_wrapper#7| state) (|poly_wrapper#2| state) (ite (|poly_wrapper#6| state) #b01111111111111111 #b00000000000000000))))) ; mod.y
(define-fun |poly_wrapper#11| ((state |poly_wrapper_s|)) (_ BitVec 10) (bvsub #b0100000000 (concat #b00 (|poly_wrapper#0| state)))) ; { $flattenorig.$sub$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:84$5_Y [16] $flattenorig.$sub$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:84$5_Y [8:0] }
(define-fun |poly_wrapper#12| ((state |poly_wrapper_s|)) (_ BitVec 17) (bvmul (concat ((_ extract 9 9) (|poly_wrapper#11| state)) (concat ((_ extract 9 9) (|poly_wrapper#11| state)) (concat ((_ extract 9 9) (|poly_wrapper#11| state)) (concat ((_ extract 9 9) (|poly_wrapper#11| state)) (concat ((_ extract 9 9) (|poly_wrapper#11| state)) (concat ((_ extract 9 9) (|poly_wrapper#11| state)) (concat ((_ extract 9 9) (|poly_wrapper#11| state)) (|poly_wrapper#11| state)))))))) (concat #b000000000 (|poly_wrapper#0| state)))) ; orig.z
(define-fun |poly_wrapper#13| ((state |poly_wrapper_s|)) Bool (bvugt (|poly_wrapper#12| state) #b01111111111111111)) ; $flattenorig.$gt$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:85$7_Y
(define-fun |poly_wrapper#14| ((state |poly_wrapper_s|)) (_ BitVec 17) (ite (|poly_wrapper#13| state) #b01111111111111111 (|poly_wrapper#12| state))) ; orig.y
(define-fun |poly_wrapper#15| ((state |poly_wrapper_s|)) Bool (= (|poly_wrapper#10| state) (|poly_wrapper#14| state))) ; eq
; yosys-smt2-output eq 1
(define-fun |poly_wrapper_n eq| ((state |poly_wrapper_s|)) Bool (|poly_wrapper#15| state))
; yosys-smt2-input sel1 1
; yosys-smt2-witness {"offset": 0, "path": ["sel1"], "smtname": "sel1", "smtoffset": 0, "type": "input", "width": 1}
(define-fun |poly_wrapper_n sel1| ((state |poly_wrapper_s|)) Bool (= ((_ extract 1 1) (|poly_wrapper#5| state)) #b1))
; yosys-smt2-input sel2 1
; yosys-smt2-witness {"offset": 0, "path": ["sel2"], "smtname": "sel2", "smtoffset": 0, "type": "input", "width": 1}
(define-fun |poly_wrapper_n sel2| ((state |poly_wrapper_s|)) Bool (= ((_ extract 0 0) (|poly_wrapper#5| state)) #b1))
; yosys-smt2-input x 8
; yosys-smt2-witness {"offset": 0, "path": ["x"], "smtname": "x", "smtoffset": 0, "type": "input", "width": 8}
(define-fun |poly_wrapper_n x| ((state |poly_wrapper_s|)) (_ BitVec 8) (|poly_wrapper#0| state))
; yosys-smt2-assert 0 $assert$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:24$3 /usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:24.9-24.20
(define-fun |poly_wrapper_a 0| ((state |poly_wrapper_s|)) Bool (or (|poly_wrapper#15| state) (not true))) ; $assert$/usr/scratch/emiller76/rewriting/verilog_examples/benchmarks/polynomials/poly_mux_wrapper.sv:24$3
(define-fun |poly_wrapper_a| ((state |poly_wrapper_s|)) Bool 
  (|poly_wrapper_a 0| state)
)
(define-fun |poly_wrapper_u| ((state |poly_wrapper_s|)) Bool true)
(define-fun |poly_wrapper_i| ((state |poly_wrapper_s|)) Bool true)
(define-fun |poly_wrapper_h| ((state |poly_wrapper_s|)) Bool true)
(define-fun |poly_wrapper_t| ((state |poly_wrapper_s|) (next_state |poly_wrapper_s|)) Bool true) ; end of module poly_wrapper
; yosys-smt2-topmod poly_wrapper
; end of yosys output

(declare-const s1 (_ BitVec 1))
(declare-const s2 (_ BitVec 1))

(define-sort a () (_ BitVec 9))
(define-fun compose ((q a) (b (_ BitVec 1)) (c (_ BitVec 1))) |poly_wrapper_s| (concat b c q))



(assert (forall ((state a)) 
    (and 
        (|poly_wrapper_a| (compose state s1 s2)) 
        (|poly_wrapper_h| (compose state s1 s2)) 
        (|poly_wrapper_u| (compose state s1 s2))
)))

"""

s = z3.Solver()
s = z3.Optimize()

s1 = z3.BitVec('s1', 1)
s2 = z3.BitVec('s2', 1)

s.from_string(smt_logic)

s.maximize(s1 + s2)

if s.check() == z3.sat:
    print("Satisfiable with model:")
    m = s.model()
    print(m[s1], m[s2])
else:
    print("Unsatisfiable")